### ISSUE TITLE
Any plans to support other languages?

### ISSUE THREAD

**Issue by erlend-sh** [sunjay/autogamer#2]
I love the idea of a Rust framework with a scripting language already plugged in! 🤩 

Have you considered supporting any language implementations besides PyO3?

There’s also [RustPython](https://github.com/RustPython/RustPython). It might be easier to use for cases like in-game scripting. See for instance: https://www.reddit.com/r/rust/comments/hgtuu5/announcement_wasiprocess_run_wasi_modules_as/

It’s been done before in [pyckitup](https://github.com/pickitup247/pyckitup) by the RustPython contributors @0b01 and @coolreader18

rlua has some reference implementations out there: 
https://github.com/Grokmoo/sulis
https://github.com/redcodestudios/rust-scripting-example

Maker of [hyperspeed](https://github.com/InquisitivePenguin/hyperspeed) @InquisitivePenguin might also have some know-how to share here?

Lastly, there’s [Mun](https://mun-lang.org/). It can’t do a whole lot yet, but that should hopefully reduce the scope of the integration work.

**Comment by sunjay** [comment]
Hello!

**Comment by sunjay** [comment]
Hello! I am only planning to support Python at this time. This project is not actually a Rust game engine. It's a Python game engine that happens to be written mostly in Rust. I'm using PyO3 instead of RustPython because I wanted to create a Python native extension module, not embed Python into a Rust app. 

Thanks for your questions. I'm glad you're excited! There's still a long way to go, but I think it will be worth it. :)
